ci: publish all builds to GH Pages

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -87,10 +87,47 @@ jobs:
         with:
           package_name: ${{ matrix.package }}
 
+  preview:
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - test
+    if: ${{ needs.build.outputs.any-workspace == 'true' }}
+    strategy:
+      fail-fast: false
+      matrix:
+        package: ${{ fromJSON(needs.build.outputs.packages) }}
+        exclude:
+          - package: global
+          - package: any-workspace
+    name: Test ${{ matrix.package }}
+    steps:
+      - name: Determine GitHub Pages directory name
+        id: branch_dir_name
+        run: |
+          if [ "$GITHUB_REF_NAME" == "develop" ]; then
+            echo "result=."
+          else
+            echo "result=${GITHUB_REF_NAME//[^A-Za-z0-9._-]/_}"
+          fi | tee --append "$GITHUB_OUTPUT"
+      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
+        with:
+          name: build
+          path: packages
+      - name: Deploy ${{ matrix.package }} testing playground to GitHub Pages
+        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ./packages/${{ matrix.package }}/playground
+          destination_dir: "${{steps.branch_dir_name.outputs.result}}/${{ matrix.package }}"
+          full_commit_message: "Build for ${{ github.sha }} ${{ github.event.head_commit.message }}"
+
   results:
     name: Results
     runs-on: ubuntu-latest
-    needs: test
+    needs:
+      - test
+      - preview
     if: ${{ always() }}
     steps:
       - run: |
@@ -106,6 +143,22 @@ jobs:
               ;;
             *)
               echo "Tests failed."
+              exit 1
+              ;;
+          esac
+      - run: |
+          case "${{ needs.preview.result }}" in
+            success)
+              echo "GitHub Pages previews published successfully."
+              exit 0
+              ;;
+            skipped)
+              echo "Previews were unnecessary for these changes, so they were skipped."
+              echo "If this is unexpected, check the path filters."
+              exit 0
+              ;;
+            *)
+              echo "Publishing GitHub Pages previews failed."
               exit 1
               ;;
           esac
